version: "3.8"

services:
  app:
    image: node:20
    working_dir: /app
    command: command: sh -c "git clone https://github.com/rikigohain0028/Recoonlytics.git . \
&& npm install \
&& cd client && npm install && npm run build \
&& cd ../server && npm install \
&& cd .. && npm run dev"


